{
 "title": "SERVICE_NAME",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "query": "SERVICE_NAME" },
   { "name": "quantile", "query": "0.5,0.8,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"POD\",container!=\"\",pod=~\"$app.*\"}",
       "legendFormat": "{{pod}} - Usage"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=~\"$app.*\", container!=\"\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total{pod=~\"$app.*\", container!=\"\"}[5m])) by (container, pod)",
       "legendFormat": "{{container}} in {{pod}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$app.*\", image!=\"\", container!=\"POD\"}[5m])) by (pod, container)",
       "legendFormat": "{{container}} in {{pod}}"
      }
     ]
    },
    {
     "title": "Ingress Error Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$app\", status!~\"(2).*\"}[2m])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{pod=~\"$app.*\",pod!~\".*dafka.*\"})",
       "legendFormat": "main"
      },
      {
       "expr": "count(kube_pod_info{pod=~\"$app.*\",pod=~\".*dafka-consumer.*\"})",
       "legendFormat": "consumer"
      },
      {
       "expr": "count(kube_pod_info{pod=~\"$app.*\",pod=~\".*dafka-producer.*\"})",
       "legendFormat": "producer"
      }
     ]
    },
    {
     "title": "Pod Container Restarts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"$app-.*\"}[2m])) by (container, pod)",
       "legendFormat": "{{container}} in {{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Consumer Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(process_batch_execution_time_count{app=\"$app-dafka-consumer\"}[5m]))",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Consumer Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(process_batch_execution_time_bucket{app=\"$app-dafka-consumer\"}[5m])) by (le))",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Consumer Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(message_latency_bucket{app=\"$app-dafka-consumer\"}[5m])) by (le, topic))",
     "legendFormat": "{{topic}} latnecy"
    }
   ]
  },
  {
   "title": "Consumer Retries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(target_execution_rerty{app=\"$app-dafka-consumer\"}[5m])) by (attempt)",
     "legendFormat": "attempt {{attempt}}"
    }
   ]
  },
  {
   "title": "Retry Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(retry_produced{app=\"$app-dafka-consumer\"}[5m]))",
     "legendFormat": "retry topic"
    }
   ]
  },
  {
   "title": "Dead Letter Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dead_letter_produced{app=\"$app-dafka-consumer\"}[5m]))",
     "legendFormat": "dead letter"
    }
   ]
  },
  {
   "title": "Topics Consumption Lag",
   "type": "timeseries",
   "description": "This shows the dafka consumer lag for each topic that is consumed by this service",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_topic_sum_lag{group=\"$app\"}) by (topic)"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "HTTP Requests Count / Minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{app=\"$app\", status_code!~\"(4|5)..\"}[5m])) by (method, path, status_code)",
     "legendFormat": "count"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"$app\"}[5m])) by (method, path, status_code)",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "HTTP Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(http_request_duration_seconds_bucket{app=\"$app\"}[5m])) by (status_code, path, method, le))"
    }
   ]
  },
  {
   "title": "HTTP Error Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{app=\"$app\", status_code!~\"(2)..\"}[5m])) by (method, path, status_code)",
     "legendFormat": "count {{status_code}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"$app\", status_code!~\"(2)..\"}[5m])) by (method, path, status_code)",
     "legendFormat": "rate {{status_code}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "API Success Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(station_api_count{app=\"$app\", result=\"success\"}[5m])) by (method)",
     "legendFormat": "station-api {{method}} "
    },
    {}
   ]
  },
  {
   "title": "API Error Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(station_api_count{app=\"$app\", result=\"error\"}[5m])) by (method)",
     "legendFormat": "station-api {{method}}"
    }
   ]
  }
 ]
}